# Generated by Django 6.0.7 on 2026-07-20 09:40

import django.db.models.deletion
import funding.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=funding.models.generate_access_token, editable=False, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('proposal_filename', models.CharField(max_length=255)),
                ('proposal_mimetype', models.CharField(max_length=255)),
                ('proposal_blob', models.BinaryField()),
                ('state', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('refused', 'Refused')], default='submitted', max_length=16)),
                ('decision_comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('upfront_invoice_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('upfront_invoice_mimetype', models.CharField(blank=True, max_length=255, null=True)),
                ('upfront_invoice_blob', models.BinaryField(blank=True, null=True)),
                ('upfront_invoice_received_at', models.DateTimeField(blank=True, null=True)),
                ('work_approved_at', models.DateTimeField(blank=True, null=True)),
                ('work_approval_comment', models.TextField(blank=True, null=True)),
                ('final_invoice_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('final_invoice_mimetype', models.CharField(blank=True, max_length=255, null=True)),
                ('final_invoice_blob', models.BinaryField(blank=True, null=True)),
                ('final_invoice_received_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_applications', to=settings.AUTH_USER_MODEL)),
                ('work_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_approved_applications', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='funding.process')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
