# Generated by Django 6.0.7 on 2026-07-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_rename_process_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='budget',
        ),
    ]
